// Generated by `pnpm gen:scripts` from kill-stale-renderer.sh: edit that file, then run it again.
export const KILL_STALE_RENDERER_SCRIPT = "#!/bin/bash\n# Frees the port from a renderer an older runtime left behind; the bracket keeps pkill off this shell.\n# Env: RENDER_PROFILE.\npkill -f -- \"--user-data-dir=${RENDER_PROFILE%?}[${RENDER_PROFILE: -1}]\" || true\nsleep 0.3\n"
