// Generated by `pnpm gen:scripts` from wait-renderer.sh: edit that file, then run it again.
export const WAIT_RENDERER_SCRIPT = "#!/bin/bash\n# Waits up to 20 s for the renderer's DevTools endpoint. Env: RENDER_PORT.\nfor _ in $(seq 1 200); do\n  curl -fsS -m 1 \"http://127.0.0.1:$RENDER_PORT/json/version\" >/dev/null 2>&1 && exit 0\n  sleep 0.1\ndone\nexit 1\n"
