type Json = Record<string, unknown>

export type SchemaFlavor = 'openai' | 'anthropic'

/** Annotations no provider needs; some OpenAI-compatible backends reject them outright. */
const DROPPED_KEYWORDS = new Set(['$schema', '$id', '$comment', '$anchor', '$dynamicAnchor', 'examples'])
/** Rejected by several OpenAI-compatible backends (Gemini, older vLLM builds) in function parameters. */
const OPENAI_DROPPED_KEYWORDS = new Set([
  '$dynamicRef',
  'contentMediaType',
  'contentEncoding',
  'readOnly',
  'writeOnly',
  'deprecated',
  'unevaluatedProperties',
  'unevaluatedItems',
  'dependentSchemas',
  'dependentRequired',
  'if',
  'then',
  'else',
])
const MAX_REF_DEPTH = 8

const isObject = (value: unknown): value is Json =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

function resolvePointer(root: Json, ref: string): unknown {
  if (!ref.startsWith('#/')) return undefined
  let node: unknown = root
  for (const raw of ref.slice(2).split('/')) {
    const key = decodeURIComponent(raw).replace(/~1/g, '/').replace(/~0/g, '~')
    if (!isObject(node)) return undefined
    node = node[key]
  }
  return node
}

/**
 * Tool input schema as the providers accept it. MCP servers send arbitrary JSON Schema (often
 * generated by zod or pydantic): local `$ref`s are inlined (recursive ones end as an open schema),
 * annotations and keywords providers reject are dropped, and the root is always an object schema
 * (a root `anyOf`/`oneOf`/`allOf` is not accepted by OpenAI nor Anthropic).
 */
export function cleanToolSchema(schema: unknown, flavor: SchemaFlavor): Json {
  const root = isObject(schema) ? schema : {}
  const visit = (node: unknown, depth: number, seen: ReadonlySet<string>): unknown => {
    if (Array.isArray(node)) return node.map((item) => visit(item, depth, seen))
    if (!isObject(node)) return node
    if (typeof node.$ref === 'string') {
      const ref = node.$ref
      const target = resolvePointer(root, ref)
      const { $ref: _ref, ...siblings } = node
      if (target === undefined || seen.has(ref) || depth >= MAX_REF_DEPTH) {
        return visit(siblings, depth, seen)
      }
      const resolved = visit(target, depth + 1, new Set([...seen, ref]))
      return isObject(resolved) ? { ...resolved, ...(visit(siblings, depth, seen) as Json) } : resolved
    }
    const out: Json = {}
    for (const [key, value] of Object.entries(node)) {
      if (DROPPED_KEYWORDS.has(key) || key === '$defs' || key === 'definitions') continue
      if (flavor === 'openai' && OPENAI_DROPPED_KEYWORDS.has(key)) continue
      if (value === undefined) continue
      if (key === 'properties' || key === 'patternProperties') {
        out[key] = Object.fromEntries(
          Object.entries(isObject(value) ? value : {}).map(([name, sub]) => [name, visit(sub, depth, seen)]),
        )
      } else if (key === 'enum' || key === 'const' || key === 'default' || key === 'required') {
        out[key] = value
      } else {
        out[key] = visit(value, depth, seen)
      }
    }
    return out
  }
  const cleaned = visit(root, 0, new Set()) as Json
  for (const key of ['description', 'title']) if (cleaned[key] === undefined) delete cleaned[key]
  const hasCombinator = ['anyOf', 'oneOf', 'allOf'].some((k) => k in cleaned)
  if (cleaned.type !== 'object' || hasCombinator) {
    // Not an object schema at the root: accept any object and keep the original as documentation.
    const { anyOf, oneOf, allOf, ...rest } = cleaned
    const variants = anyOf ?? oneOf ?? allOf
    const merged = Array.isArray(variants) ? mergeObjectVariants(variants) : null
    return {
      type: 'object',
      properties: { ...(isObject(rest.properties) ? rest.properties : {}), ...(merged ?? {}) },
      ...(typeof rest.description === 'string' ? { description: rest.description } : {}),
    }
  }
  if (!isObject(cleaned.properties)) cleaned.properties = {}
  if (Array.isArray(cleaned.required)) {
    const props = cleaned.properties as Json
    cleaned.required = (cleaned.required as unknown[]).filter((r) => typeof r === 'string' && r in props)
  }
  return cleaned
}

/** Union of the properties of object variants (`anyOf` of objects at the root), all optional. */
function mergeObjectVariants(variants: unknown[]): Json | null {
  const merged: Json = {}
  for (const variant of variants) {
    if (!isObject(variant) || !isObject(variant.properties)) continue
    Object.assign(merged, variant.properties)
  }
  return Object.keys(merged).length ? merged : null
}

interface ToolLike {
  name: string
  description: string
  inputSchema: Record<string, unknown>
}

/** OpenAI Chat Completions function tool. */
export function toOpenAiTool(tool: ToolLike): {
  type: 'function'
  function: { name: string; description: string; parameters: Json }
} {
  return {
    type: 'function',
    function: {
      name: tool.name,
      description: tool.description,
      parameters: cleanToolSchema(tool.inputSchema, 'openai'),
    },
  }
}

/** Anthropic Messages tool (`input_schema` must be an object schema). */
export function toAnthropicTool(tool: ToolLike): {
  name: string
  description: string
  input_schema: Json & { type: 'object' }
} {
  return {
    name: tool.name,
    description: tool.description,
    input_schema: cleanToolSchema(tool.inputSchema, 'anthropic') as Json & { type: 'object' },
  }
}
