// Generated by `pnpm gen:scripts` from mirror-list.sh: edit that file, then run it again.
export const MIRROR_LIST_SCRIPT =
  '#!/bin/bash\n# Prints `<slug> <hash>` for every skill mirrored under $MILIBOT_SKILLS_ROOT.\nROOT="${MILIBOT_SKILLS_ROOT:?}"\n[ -d "$ROOT" ] || exit 0\nfor d in "$ROOT"/*/; do\n  [ -d "$d" ] || continue\n  printf \'%s %s\\n\' "$(basename "$d")" "$(cat "$d${HASH_FILE:?}" 2>/dev/null || echo -)"\ndone\n'
