import { readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { basename, extname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const RUNTIME = fileURLToPath(new URL('../src/runtime/', import.meta.url))
const SCRIPT_FILE = /^[a-z0-9-]+\.(sh|js)$/

/** `relay.js` → `RELAY_SCRIPT`, `changes-script.sh` → `CHANGES_SCRIPT`. */
export function scriptConstant(file: string): string {
  const base = basename(file, extname(file)).replace(/-script$/, '')
  return `${base.replaceAll('-', '_').toUpperCase()}_SCRIPT`
}

function scriptDirs(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name)
    if (!statSync(path).isDirectory()) return []
    return name === 'scripts' ? [path] : scriptDirs(path)
  })
}

/** Every generated module (`<script>.generated.ts` beside each `scripts/*.{sh,js}`) with its text. */
export function generatedScripts(root = RUNTIME): Map<string, string> {
  const out = new Map<string, string>()
  for (const dir of scriptDirs(root)) {
    for (const name of readdirSync(dir).sort()) {
      if (!SCRIPT_FILE.test(name)) continue
      const text = readFileSync(join(dir, name), 'utf8')
      out.set(
        join(dir, `${basename(name, extname(name))}.generated.ts`),
        `// Generated by \`pnpm gen:scripts\` from ${name}: edit that file, then run it again.\n` +
          `export const ${scriptConstant(name)} = ${JSON.stringify(text)}\n`,
      )
    }
  }
  return out
}

/** Generated modules on disk whose script is gone. */
export function orphanedModules(root = RUNTIME, expected = generatedScripts(root)): string[] {
  return scriptDirs(root).flatMap((dir) =>
    readdirSync(dir)
      .filter((name) => name.endsWith('.generated.ts'))
      .map((name) => join(dir, name))
      .filter((path) => !expected.has(path)),
  )
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const expected = generatedScripts()
  for (const [path, text] of expected) writeFileSync(path, text)
  for (const path of orphanedModules(RUNTIME, expected)) rmSync(path)
  console.log(`wrote ${expected.size} script modules`)
}
